services:
  agent:
    build:
      context: .
    container_name: adk_agent
    restart: unless-stopped
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_GENAI_USE_VERTEXAI=FALSE
      - MCP_SERVER_URL=http://host.docker.internal
      - MCP_SERVER_PORT=8001
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
